spring.application.name=App

spring.security.user.name=dev
spring.security.user.password=build

spring.datasource.url=jdbc:postgresql://localhost:5432/authservice
spring.datasource.username=postgres
spring.datasource.password=build@dev

jwt.secret=R8x0s4ZV2YJb9Qk3u7K6e1mTgPpWcA5HnFqLr9XjC0D=
jwt.expiration=900000

spring.devtools.restart.enabled=false

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE